service: user-management-service

provider:
  name: aws
  runtime: nodejs8.10
  profile: infusion-workshop
  stage: ${env:USER}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DeleteItem
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        Fn::GetAtt:
          - Table
          - Arn
  environment:
    TABLE_NAME:
      Ref: Table

functions:
  addUser:
    handler: addUser.handler
    events:
      - http:
          path: users/{id}
          method: put
  deleteUser:
    handler: deleteUser.handler
    events:
      - http:
          path: users/{id}
          method: delete
  getUser:
    handler: getUser.handler
    events:
      - http:
          path: users/{id}
          method: get

custom:
  table: ${self:provider.stage}-users

resources:
  Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.table}
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

