service: user-management-service

provider:
  name: aws
  runtime: nodejs8.10
  profile: infusion-workshop
  stage: ${env:USER}

functions:
  addUser:
    handler: addUser.handler
    events:
      - http:
          path: users/{id}
          method: put
  deleteUser:
    handler: deleteUser.handler
    events:
      - http:
          path: users/{id}
          method: delete
  getUser:
    handler: getUser.handler
    events:
      - http:
          path: users/{id}
          method: get
